/-
Copyright (c) 2026 Antoine du Fresne von Hohenesche. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import GraphLib.Graph.Basic
import GraphLib.Playground.Dilworth_Mirsky
import Mathlib.Data.Real.Basic
import Mathlib.Order.Interval.Set.OrdConnected
import Mathlib.Data.Nat.Lattice
import Mathlib.Data.Finset.Card
import Mathlib.Order.ConditionallyCompleteLattice.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Fintype.EquivFin
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset

/-!
# Playground: interval graphs are perfect

**The result.** The *interval graph* `G` generated by a finite collection `𝓘` of intervals of `ℝ`
is *perfect*: on every induced subgraph `H` the chromatic number equals the clique number,
`χ(H) = ω(H)`. The headline theorem is `isPerfect_intervalGraph`.

**Method.** We take the high-level route: intervals graph is hereditary (i.e. an induced subgraph
of an interval graph is also an interval graph), so it suffices to prove `χ(G) = ω(G)` for an
arbitrary interval graph. Then we order the intervals by "entirely before", so that
adjacency in `G` implies *incomparability*; then `χ(G) = ω(G)` follows from `χ(G) ≥ ω(G)`
(general inequality) and `χ(G) ≤ ω(G)` follows from the application Dilworth's theorem.
Dilworth is imported from `GraphLib/Playground/Dilworth_Mirsky.lean`.

A corollary of this result is the statement "a finite family of intervals splits into `ω`
pairwise-disjoint subfamilies" is just the `ω`-colouring repackaged — a special case of the
general colouring corollary in §D (`ncard_le_chromaticNum_mul_independenceNum`).

**For colleagues.** Declarations carrying a `-- #general` comment are not specific to interval
graphs: they are notions/facts about arbitrary (finite) simple graphs that should live in the core
graph library, not in this playground. A few tagged `#general (specialised)` are currently stated
only for `intervalGraph` but hold for every finite simple graph. We deliberately do not
generalise them here — `grep '#general'` lists them all. --> It could be great to formalise
those statements.


To do: Make this more general: our result is simply the result of the
Perfection of comparability graphs (it suffices again to prove `χ = ω` for
the comparability graph of a poset, which is Dilworth's theorem because
comparability graph is hereditary).
-/

namespace GraphLib.Playground
open GraphLib

-- ### The interval graph `G = ⟨𝓘, E, ⊂⟩`

/-- The interval graph of a finite collection `𝓘` of intervals: vertices are the intervals,
and two *distinct* intervals are adjacent iff they intersect. -/
def intervalGraph (𝓘 : Finset (Set ℝ)) : SimpleGraph (Set ℝ) where
  vertexSet := ↑𝓘
  edgeSet := {e | ∃ A ∈ 𝓘, ∃ B ∈ 𝓘, A ≠ B ∧ (A ∩ B).Nonempty ∧ e = s(A, B)}
  incidence' := by
    rintro e ⟨A, hA, B, hB, _, _, rfl⟩ v hv
    rw [Sym2.mem_iff] at hv
    rcases hv with rfl | rfl
    · exact Finset.mem_coe.mpr hA
    · exact Finset.mem_coe.mpr hB
  loopless' := by
    rintro e ⟨A, _, B, _, hne, _, rfl⟩
    rw [Sym2.mk_isDiag_iff]
    exact hne

namespace SimpleGraph
variable {α : Type*}

-- ### Clique and clique number `ω`

-- #general
/-- `C` is a clique of `G`: a set of vertices that are pairwise adjacent. -/
def IsClique (G : SimpleGraph α) (C : Set α) : Prop :=
  C ⊆ V(G) ∧ ∀ ⦃a⦄, a ∈ C → ∀ ⦃b⦄, b ∈ C → a ≠ b → s(a, b) ∈ E(G)

-- #general
/-- The clique number `ω(G)`: the supremum of cardinalities of finite cliques. -/
noncomputable def cliqueNum (G : SimpleGraph α) : ℕ :=
  sSup {n | ∃ C : Finset α, IsClique G ↑C ∧ C.card = n}

-- ### Proper coloring and chromatic number `χ`

-- #general
/-- `f` is a proper coloring of `G`: adjacent vertices receive distinct colors. -/
def IsProperColoring {κ : Type*} (G : SimpleGraph α) (f : ↥(V(G)) → κ) : Prop :=
  ∀ a b : ↥(V(G)), s(↑a, ↑b) ∈ E(G) → f a ≠ f b

-- #general
/-- The chromatic number `χ(G)`: the least `n` admitting a proper colouring of the vertices into
`Fin n`. -/
noncomputable def chromaticNum (G : SimpleGraph α) : ℕ :=
  sInf {n | ∃ f : ↥(V(G)) → Fin n, IsProperColoring G f}

-- ### Perfection

-- #general (also: should be `@[ext]` on the upstream `SimpleGraph` structure)
/-- Two graphs on `α` are equal once their vertex and edge sets agree (the structural axioms are
propositions, hence proof-irrelevant). -/
lemma ext' {G H : SimpleGraph α} (hv : G.vertexSet = H.vertexSet) (he : G.edgeSet = H.edgeSet) :
    G = H := by
  obtain ⟨v₁, e₁, _, _⟩ := G
  obtain ⟨v₂, e₂, _, _⟩ := H
  obtain rfl : v₁ = v₂ := hv
  obtain rfl : e₁ = e₂ := he
  rfl

-- #general
/-- The subgraph of `G` induced on a vertex subset `W`: keep `W` as vertices and exactly the edges
of `G` both of whose endpoints lie in `W`. -/
def induce (G : SimpleGraph α) (W : Set α) : SimpleGraph α where
  vertexSet := W
  edgeSet := {e ∈ G.edgeSet | ∀ v ∈ e, v ∈ W}
  incidence' := fun _ he _ hv => he.2 _ hv
  loopless' := fun _ he => G.loopless' _ he.1

-- #general
/-- A simple graph is *perfect* when every induced subgraph has equal chromatic and clique
numbers. -/
def IsPerfect (G : SimpleGraph α) : Prop :=
  ∀ ⦃W⦄, W ⊆ V(G) → chromaticNum (induce G W) = cliqueNum (induce G W)

end SimpleGraph

-- ## A. Analytic helpers and graph lemmas

open SimpleGraph Set

/-! ### Unfolding the interval graph's vertex and edge sets -/

@[simp] lemma vertexSet_intervalGraph (𝓘 : Finset (Set ℝ)) :
    V(intervalGraph 𝓘) = (↑𝓘 : Set (Set ℝ)) := rfl

@[simp] lemma edgeSet_intervalGraph (𝓘 : Finset (Set ℝ)) :
    E(intervalGraph 𝓘) =
      {e | ∃ A ∈ 𝓘, ∃ B ∈ 𝓘, A ≠ B ∧ (A ∩ B).Nonempty ∧ e = s(A, B)} := rfl

/-- adjacency in the interval graph: `s(A,B)` is an edge iff `A, B` are distinct members of
`𝓘` that intersect. This is the direct Lean reading of the set-theoretic edge relation. -/
lemma mem_edgeSet_intervalGraph {𝓘 : Finset (Set ℝ)} {A B : Set ℝ} :
    s(A, B) ∈ E(intervalGraph 𝓘) ↔ A ∈ 𝓘 ∧ B ∈ 𝓘 ∧ A ≠ B ∧ (A ∩ B).Nonempty := by
  rw [edgeSet_intervalGraph, Set.mem_setOf_eq]
  constructor
  · rintro ⟨A', hA', B', hB', hne', hAB', he⟩
    rw [Sym2.eq_iff] at he
    rcases he with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact ⟨hA', hB', hne', hAB'⟩
    · refine ⟨hB', hA', hne'.symm, ?_⟩
      rwa [Set.inter_comm]
  · rintro ⟨hA, hB, hne, hAB⟩
    exact ⟨A, hA, B, hB, hne, hAB, rfl⟩

/-! ### Clique bookkeeping -/

-- #general (specialised) — `IsClique G ∅` for any graph `G`
/-- The empty set is a clique of the interval graph. -/
lemma isClique_empty (𝓘 : Finset (Set ℝ)) :
    IsClique (intervalGraph 𝓘) (↑(∅ : Finset (Set ℝ))) := by
  rw [Finset.coe_empty]; exact ⟨Set.empty_subset _, fun a ha => absurd ha (Set.notMem_empty a)⟩

-- #general (specialised) — clique cardinalities are bounded above for any finite-vertex graph
/-- The set of clique cardinalities is bounded above: every clique is a subfamily of `𝓘`, so has at
most `𝓘.card` members. (Needed so that the `sSup` defining `cliqueNum` behaves as a maximum.) -/
lemma cliqueNum_bddAbove (𝓘 : Finset (Set ℝ)) :
    BddAbove {n | ∃ C : Finset (Set ℝ), IsClique (intervalGraph 𝓘) ↑C ∧ C.card = n} := by
  refine ⟨𝓘.card, ?_⟩
  rintro n ⟨C, ⟨hsub, _⟩, rfl⟩
  refine Finset.card_le_card fun a ha => ?_
  have : a ∈ V(intervalGraph 𝓘) := hsub (Finset.mem_coe.mpr ha)
  rwa [vertexSet_intervalGraph, Finset.mem_coe] at this

-- #general (specialised) — holds for any finite-vertex graph
/-- The cardinality of a clique is bounded above by the clique number. -/
lemma card_le_cliqueNum {𝓘 : Finset (Set ℝ)} {Q : Finset (Set ℝ)}
    (h : IsClique (intervalGraph 𝓘) ↑Q) : Q.card ≤ cliqueNum (intervalGraph 𝓘) := by
  apply le_csSup (cliqueNum_bddAbove 𝓘); exact ⟨Q, h, rfl⟩

/-! ## B. `χ(G) ≤ ω(G)` via Dilworth's theorem

Order the intervals by "entirely before" (`intervalLE`): two *distinct* intervals are comparable
iff disjoint, so adjacency in `intervalGraph` is exactly incomparability. Dilworth's theorem (via
`dilworth_rel`) yields an antichain `A` and a chain cover `𝒞` of equal size: the antichain is a
clique (`|A| ≤ ω`) and the chain cover is a proper colouring (`χ ≤ |𝒞|`), so `χ ≤ |𝒞| = |A| ≤ ω`. -/

/-- The interval order: `A ≼ B` iff `A = B`, or `B` is non-empty and every point of `A` is below
every point of `B` ("`A` entirely before `B`"). The `B.Nonempty` guard makes `∅` a global minimum,
so this is a genuine partial order on *all* of `Set ℝ` (empty intervals included). -/
def intervalLE (A B : Set ℝ) : Prop := A = B ∨ (B.Nonempty ∧ ∀ x ∈ A, ∀ y ∈ B, x < y)

lemma intervalLE_refl (A : Set ℝ) : intervalLE A A := Or.inl rfl

lemma intervalLE_trans {A B C : Set ℝ} (hAB : intervalLE A B) (hBC : intervalLE B C) :
    intervalLE A C := by
  rcases hAB with rfl | ⟨hBne, hAB⟩
  · exact hBC
  · rcases hBC with rfl | ⟨hCne, hBC⟩
    · exact Or.inr ⟨hBne, hAB⟩
    · obtain ⟨z, hz⟩ := hBne
      exact Or.inr ⟨hCne, fun x hx y hy => lt_trans (hAB x hx z hz) (hBC z hz y hy)⟩

lemma intervalLE_antisymm {A B : Set ℝ} (hAB : intervalLE A B) (hBA : intervalLE B A) : A = B := by
  rcases hAB with rfl | ⟨hBne, hAB⟩
  · rfl
  · rcases hBA with rfl | ⟨hAne, hBA⟩
    · rfl
    · obtain ⟨x, hx⟩ := hAne; obtain ⟨y, hy⟩ := hBne
      exact absurd (lt_trans (hAB x hx y hy) (hBA y hy x hx)) (lt_irrefl x)

/-- `∅` is the least interval. -/
lemma intervalLE_empty (B : Set ℝ) : intervalLE ∅ B :=
  B.eq_empty_or_nonempty.elim (fun h => Or.inl h.symm)
    fun h => Or.inr ⟨h, fun x hx => absurd hx (Set.notMem_empty x)⟩

/-- Comparable intervals are equal or disjoint (so within a chain, distinct intervals are
disjoint). -/
lemma eq_or_disjoint_of_intervalLE {A B : Set ℝ} (h : intervalLE A B) :
    A = B ∨ ¬ (A ∩ B).Nonempty :=
  h.imp_right fun ⟨_, hAB⟩ ⟨z, hzA, hzB⟩ => absurd (hAB z hzA z hzB) (lt_irrefl z)

/-- **The geometric heart.** Two non-empty intervals, neither entirely before the other, overlap. -/
lemma inter_nonempty_of_not_intervalLE {A B : Set ℝ} (hA : A.OrdConnected) (hB : B.OrdConnected)
    (hAB : ¬ ∀ x ∈ A, ∀ y ∈ B, x < y) (hBA : ¬ ∀ x ∈ B, ∀ y ∈ A, x < y) :
    (A ∩ B).Nonempty := by
  push Not at hAB hBA
  obtain ⟨a, ha, b, hb, hba⟩ := hAB
  obtain ⟨b', hb', a', ha', ha'b'⟩ := hBA
  rcases le_total a' b with h | h
  · exact ⟨b, hA.out ha' ha ⟨h, hba⟩, hb⟩
  · exact ⟨a', ha', hB.out hb hb' ⟨h, ha'b'⟩⟩

/-- Distinct *incomparable* intervals overlap (within an antichain, distinct intervals meet); `∅` is
the global minimum, hence comparable to everything. -/
lemma inter_nonempty_of_incomp {A B : Set ℝ} (hA : A.OrdConnected) (hB : B.OrdConnected)
    (hnAB : ¬ intervalLE A B) (hnBA : ¬ intervalLE B A) : (A ∩ B).Nonempty := by
  have hAne : A.Nonempty := by
    rcases A.eq_empty_or_nonempty with rfl | h
    exacts [absurd (intervalLE_empty B) hnAB, h]
  have hBne : B.Nonempty := by
    rcases B.eq_empty_or_nonempty with rfl | h
    exacts [absurd (intervalLE_empty A) hnBA, h]
  exact inter_nonempty_of_not_intervalLE hA hB
    (fun h => hnAB (Or.inr ⟨hBne, h⟩)) (fun h => hnBA (Or.inr ⟨hAne, h⟩))

/-- **Dilworth's theorem, relation form.** `dilworth` for an explicit partial-order relation `r`,
installed as a `PartialOrder` on the *abstract* `α` — which has no ambient `≤`/`<`, so the default
`lt` synthesizes and there is no instance clash (unlike installing it directly on `Set ℝ`, whose
`<` is `⊂`). The local instance makes `(· ≤ ·)` definitionally `r`, so `dilworth` proves the goal
outright; the conclusion is re-exposed via `r` (Mathlib's `IsAntichain`/`IsChain` at `r`). -/
theorem dilworth_rel {α : Type*} [DecidableEq α] (s : Finset α) (r : α → α → Prop)
    (hrefl : ∀ a, r a a) (htrans : ∀ a b c, r a b → r b c → r a c)
    (hantisymm : ∀ a b, r a b → r b a → a = b) :
    ∃ (A : Finset α) (𝒞 : Finset (Finset α)),
      A ⊆ s ∧ IsAntichain r ↑A ∧
      s = 𝒞.biUnion id ∧ (∀ C ∈ 𝒞, IsChain r ↑C) ∧ 𝒞.card = A.card := by
  letI : PartialOrder α :=
    { le := r, le_refl := hrefl, le_trans := htrans, le_antisymm := hantisymm }
  exact dilworth s

/-- **Dilworth applied to the interval order.** A proper colouring of the vertices into `Fin d`
together with `d ≤ ω(G)` — the whole content of `χ(G) ≤ ω(G)`. The chain cover gives the colouring
(same colour ⟹ same chain ⟹ comparable ⟹ disjoint); the antichain is a clique. -/
lemma exists_proper_coloring_le_cliqueNum (𝓘 : Finset (Set ℝ))
    (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    ∃ (d : ℕ) (f : ↥(V(intervalGraph 𝓘)) → Fin d),
      IsProperColoring (intervalGraph 𝓘) f ∧ d ≤ cliqueNum (intervalGraph 𝓘) := by
  classical
  obtain ⟨A, 𝒞, hAsub, hAanti, hcov, hchains, hcard⟩ :=
    dilworth_rel 𝓘 intervalLE intervalLE_refl (fun _ _ _ => intervalLE_trans)
      (fun _ _ => intervalLE_antisymm)
  -- every vertex lies in some chain of the cover; choose one and colour by its index
  have hmem : ∀ a : ↥(V(intervalGraph 𝓘)), ∃ C ∈ 𝒞, a.1 ∈ C := by
    rintro ⟨x, hx⟩
    rw [vertexSet_intervalGraph, Finset.mem_coe, hcov] at hx
    simpa using hx
  choose C hC haC using hmem
  refine ⟨𝒞.card, fun a => 𝒞.equivFin ⟨C a, hC a⟩, fun a b hab heq => ?_, ?_⟩
  · obtain ⟨_, _, hne, hmeet⟩ := mem_edgeSet_intervalGraph.mp hab
    have hCab : C a = C b := congrArg Subtype.val (𝒞.equivFin.injective heq)
    have hbCa : b.1 ∈ C a := by rw [hCab]; exact haC b
    rcases hchains (C a) (hC a) (haC a) hbCa hne with h | h <;>
      rcases eq_or_disjoint_of_intervalLE h with he | hd
    · exact hne he
    · exact hd hmeet
    · exact hne he.symm
    · exact hd (by rwa [Set.inter_comm])
  · rw [hcard]
    refine card_le_cliqueNum ⟨fun B hB => hAsub hB, fun B hB D hD hBD => ?_⟩
    rw [mem_edgeSet_intervalGraph]
    exact ⟨hAsub hB, hAsub hD, hBD, inter_nonempty_of_incomp (hI B (hAsub hB)) (hI D (hAsub hD))
      (hAanti hB hD hBD) (hAanti hD hB hBD.symm)⟩

/-! ## C. The headline results: `χ = ω` and perfection

`χ ≤ ω` is §B; `ω ≤ χ` holds for every finite graph (a clique injects into the colours). Hence
`χ = ω` (`chromaticNum_eq_cliqueNum_intervalGraph`), and by heredity (an induced subgraph of an
interval graph is an interval graph, `induce_intervalGraph`) this lifts to perfection
(`isPerfect_intervalGraph`). -/

/-- A proper colouring of the vertices into `Fin (χ G)` exists (the `χ`-set is non-empty by §B, so
its `sInf` is attained). -/
lemma exists_coloring_chromaticNum (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    ∃ f : ↥(V(intervalGraph 𝓘)) → Fin (chromaticNum (intervalGraph 𝓘)),
      IsProperColoring (intervalGraph 𝓘) f := by
  obtain ⟨d, f, hf, _⟩ := exists_proper_coloring_le_cliqueNum 𝓘 hI
  have hmem : d ∈ {n | ∃ f : ↥(V(intervalGraph 𝓘)) → Fin n, IsProperColoring (intervalGraph 𝓘) f} :=
    ⟨f, hf⟩
  exact Nat.sInf_mem ⟨d, hmem⟩

/-- **Key inequality.** For an interval graph, `χ(G) ≤ ω(G)` (Dilworth, §B). -/
theorem chromaticNum_le_cliqueNum_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    chromaticNum (intervalGraph 𝓘) ≤ cliqueNum (intervalGraph 𝓘) := by
  obtain ⟨d, f, hf, hd⟩ := exists_proper_coloring_le_cliqueNum 𝓘 hI
  have hmem : d ∈ {n | ∃ f : ↥(V(intervalGraph 𝓘)) → Fin n, IsProperColoring (intervalGraph 𝓘) f} :=
    ⟨f, hf⟩
  exact le_trans (Nat.sInf_le hmem) hd

-- #general (specialised) — `ω(G) ≤ χ(G)` for any finite graph (the proof never uses intervals)
/-- The reverse inequality `ω(G) ≤ χ(G)`, holding for every (finite) graph: a clique injects into
the colours. -/
theorem cliqueNum_le_chromaticNum_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    cliqueNum (intervalGraph 𝓘) ≤ chromaticNum (intervalGraph 𝓘) := by
  classical
  obtain ⟨f, hf⟩ := exists_coloring_chromaticNum 𝓘 hI
  apply csSup_le
  · exact ⟨0, ∅, isClique_empty 𝓘, Finset.card_empty⟩
  · rintro m ⟨C, hC, rfl⟩
    have key : ∀ A ∈ (↑C : Set (Set ℝ)), A ∈ V(intervalGraph 𝓘) := fun A hA => hC.1 hA
    calc C.card
        ≤ (Finset.range (chromaticNum (intervalGraph 𝓘))).card :=
          Finset.card_le_card_of_injOn
            (fun A => if h : A ∈ V(intervalGraph 𝓘) then (f ⟨A, h⟩).1 else 0)
            (fun A hA => Finset.mem_coe.mpr (Finset.mem_range.mpr (by
              simp only [dif_pos (key A hA)]; exact (f ⟨A, key A hA⟩).2)))
            (fun A hA B hB hAB => by
              simp only [dif_pos (key A hA), dif_pos (key B hB)] at hAB
              by_contra hne2
              exact hf ⟨A, key A hA⟩ ⟨B, key B hB⟩ (hC.2 hA hB hne2) (Fin.val_injective hAB))
      _ = chromaticNum (intervalGraph 𝓘) := Finset.card_range _

/-- **Single-graph equality.** `χ(G) = ω(G)` for an interval graph. -/
theorem chromaticNum_eq_cliqueNum_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    chromaticNum (intervalGraph 𝓘) = cliqueNum (intervalGraph 𝓘) :=
  le_antisymm (chromaticNum_le_cliqueNum_intervalGraph 𝓘 hI)
    (cliqueNum_le_chromaticNum_intervalGraph 𝓘 hI)

open Classical in
/-- **Heredity.** An induced subgraph of an interval graph is again an interval graph: inducing on
a vertex subset `W ⊆ ↑𝓘` gives the interval graph of the subfamily `𝓘.filter (· ∈ W)`. -/
lemma induce_intervalGraph {𝓘 : Finset (Set ℝ)} {W : Set (Set ℝ)} (hW : W ⊆ ↑𝓘) :
    induce (intervalGraph 𝓘) W = intervalGraph (𝓘.filter (· ∈ W)) := by
  apply SimpleGraph.ext'
  · change W = ↑(𝓘.filter (· ∈ W))
    rw [Finset.coe_filter]
    exact Set.ext fun A => ⟨fun h => ⟨hW h, h⟩, fun h => h.2⟩
  · change {e ∈ (intervalGraph 𝓘).edgeSet | ∀ v ∈ e, v ∈ W}
        = (intervalGraph (𝓘.filter (· ∈ W))).edgeSet
    ext e
    induction e using Sym2.ind with
    | _ A B =>
      rw [Set.mem_sep_iff,
        show (intervalGraph 𝓘).edgeSet = E(intervalGraph 𝓘) from rfl, mem_edgeSet_intervalGraph,
        show (intervalGraph (𝓘.filter (· ∈ W))).edgeSet = E(intervalGraph (𝓘.filter (· ∈ W)))
          from rfl, mem_edgeSet_intervalGraph]
      simp only [Finset.mem_filter]
      constructor
      · rintro ⟨⟨hA, hB, hne, hint⟩, hvW⟩
        exact ⟨⟨hA, hvW A (Sym2.mem_mk_left A B)⟩, ⟨hB, hvW B (Sym2.mem_mk_right A B)⟩, hne, hint⟩
      · rintro ⟨⟨hA, hAW⟩, ⟨hB, hBW⟩, hne, hint⟩
        refine ⟨⟨hA, hB, hne, hint⟩, ?_⟩
        intro v hv
        rw [Sym2.mem_iff] at hv
        rcases hv with rfl | rfl
        exacts [hAW, hBW]

/-- **The interval graph is perfect.** Every induced subgraph has `χ = ω`, by heredity
(`induce_intervalGraph`) reducing each to the single-graph
`chromaticNum_eq_cliqueNum_intervalGraph`. -/
theorem isPerfect_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    IsPerfect (intervalGraph 𝓘) := by
  classical
  intro W hW
  rw [vertexSet_intervalGraph] at hW
  rw [induce_intervalGraph hW]
  exact chromaticNum_eq_cliqueNum_intervalGraph _
    (fun A hA => hI A (Finset.mem_filter.mp hA).1)

/-! ## D. A general corollary: a colouring splits the vertices into independent sets

Not about intervals: for any graph with finite vertex set, an optimal colouring splits `V(G)` into
`χ(G)` independent classes, each of size `≤ α(G)`, giving `|V(G)| ≤ χ(G) · α(G)`. The classical
"partition into pairwise-disjoint subfamilies" is the special case `G = intervalGraph 𝓘`. -/

namespace SimpleGraph
variable {α : Type*}

-- #general
/-- `S` is an *independent set* of `G`: a set of pairwise non-adjacent vertices. -/
def IsIndependentSet (G : SimpleGraph α) (S : Set α) : Prop :=
  S ⊆ V(G) ∧ ∀ ⦃a⦄, a ∈ S → ∀ ⦃b⦄, b ∈ S → a ≠ b → s(a, b) ∉ E(G)

-- #general
/-- The independence number `α(G)`: the supremum of cardinalities of finite independent sets. -/
noncomputable def independenceNum (G : SimpleGraph α) : ℕ :=
  sSup {n | ∃ S : Finset α, IsIndependentSet G ↑S ∧ S.card = n}

end SimpleGraph

open SimpleGraph

-- #general
/-- When `V(G)` is finite, the independent-set cardinalities are bounded above by `|V(G)|`. -/
lemma independenceNum_bddAbove {α : Type*} (G : SimpleGraph α) (hV : (V(G)).Finite) :
    BddAbove {n | ∃ S : Finset α, IsIndependentSet G ↑S ∧ S.card = n} := by
  refine ⟨hV.toFinset.card, ?_⟩
  rintro n ⟨S, ⟨hSsub, _⟩, rfl⟩
  exact Finset.card_le_card fun a ha => hV.mem_toFinset.mpr (hSsub (Finset.mem_coe.mpr ha))

-- #general
/-- **Colouring bound.** For any graph with finite vertex set, `|V(G)| ≤ χ(G) · α(G)`: an optimal
proper colouring splits `V(G)` into `χ(G)` colour classes, each an independent set of size `≤ α(G)`.
The classical interval partition is the special case `G = intervalGraph 𝓘`, `χ = ω`. -/
theorem ncard_le_chromaticNum_mul_independenceNum {α : Type*} (G : SimpleGraph α)
    (hV : (V(G)).Finite) : (V(G)).ncard ≤ chromaticNum G * independenceNum G := by
  classical
  haveI : Fintype ↥(V(G)) := hV.fintype
  -- an optimal proper colouring `f : V(G) → Fin (χ G)` exists (the `χ`-set is nonempty)
  obtain ⟨f, hf⟩ : ∃ f : ↥(V(G)) → Fin (chromaticNum G), IsProperColoring G f := by
    have hmem : Fintype.card ↥(V(G)) ∈
        {n | ∃ f : ↥(V(G)) → Fin n, IsProperColoring G f} := by
      refine ⟨Fintype.equivFin ↥(V(G)), fun a b hab heq => ?_⟩
      have hab' : a = b := (Fintype.equivFin _).injective heq
      subst hab'
      exact G.loopless hab (Sym2.mk_isDiag_iff.mpr rfl)
    exact Nat.sInf_mem ⟨_, hmem⟩
  -- spread `f` to a total colour `g : α → ℕ`
  set g : α → ℕ := fun a => if h : a ∈ V(G) then (f ⟨a, h⟩).1 else 0 with hg
  have hgV : ∀ a (h : a ∈ V(G)), g a = (f ⟨a, h⟩).1 := fun a h => by simp only [hg, dif_pos h]
  -- every vertex gets a colour `< χ G`
  have hcover : ∀ a ∈ hV.toFinset, g a ∈ Finset.range (chromaticNum G) := by
    intro a ha
    have haV := hV.mem_toFinset.mp ha
    rw [Finset.mem_range, hgV a haV]
    exact (f ⟨a, haV⟩).2
  -- each colour class is an independent set, so has `≤ α(G)` elements
  have hclass : ∀ i, (hV.toFinset.filter (fun a => g a = i)).card ≤ independenceNum G := by
    intro i
    apply le_csSup (independenceNum_bddAbove G hV)
    refine ⟨hV.toFinset.filter (fun a => g a = i),
      ⟨fun a ha => ?_, fun a ha b hb hab hedge => ?_⟩, rfl⟩
    · rw [Finset.mem_coe, Finset.mem_filter] at ha
      exact hV.mem_toFinset.mp ha.1
    · rw [Finset.mem_coe, Finset.mem_filter] at ha hb
      have haV := hV.mem_toFinset.mp ha.1
      have hbV := hV.mem_toFinset.mp hb.1
      have hval : (f ⟨a, haV⟩).1 = (f ⟨b, hbV⟩).1 := by
        rw [← hgV a haV, ← hgV b hbV, ha.2, hb.2]
      exact hf ⟨a, haV⟩ ⟨b, hbV⟩ hedge (Fin.val_injective hval)
  -- sum the colour fibres
  rw [Set.ncard_eq_toFinset_card _ hV, Finset.card_eq_sum_card_fiberwise hcover]
  calc ∑ i ∈ Finset.range (chromaticNum G), (hV.toFinset.filter (fun a => g a = i)).card
      ≤ ∑ _i ∈ Finset.range (chromaticNum G), independenceNum G :=
        Finset.sum_le_sum fun i _ => hclass i
    _ = chromaticNum G * independenceNum G := by
        rw [Finset.sum_const, Finset.card_range, smul_eq_mul]

end GraphLib.Playground
