/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import GraphLib.Graph.Basic
import Mathlib.Data.EReal.Basic
import Mathlib.Data.Prod.Lex
import Mathlib.Order.Interval.Set.OrdConnected
import Mathlib.Data.Nat.Lattice
import Mathlib.Data.Finset.Max
import Mathlib.Data.Finset.Card
import Mathlib.Order.ConditionallyCompleteLattice.Basic

/-!
# Playground: interval graphs are perfect

This is a *playground* file (see `GraphLib/Playground/`): the goal is not to build a polished
piece of the library, but to stress-test the bespoke graph definitions of
`GraphLib/Graph/Basic.lean` on a small, classical result and record where the definitions are
convenient and where they create friction.

**The result.** (Problem 2.) Let `𝓘` be a finite collection of (closed) intervals of `ℝ`, and let
`k` be the maximum number of pairwise intersecting intervals in `𝓘`. Then `𝓘` can be partitioned
into `k` subcollections of pairwise disjoint intervals. Equivalently, the *interval graph* `G`
generated by `𝓘` satisfies `χ(G) = ω(G) = k`, i.e. `G` is perfect.

**The workflow.** We follow a handwritten set-theoretic proof. Each argument is reproduced
*twice*:

* `(S)` — the step phrased set-theoretically, in plain English (faithful to the source);
* `(L)` — the *same* step translated into Lean / dependent type theory, using Mathlib for the
  analytic notions (intervals, `sInf`, lexicographic order, …) and the `GraphLib` definitions
  (`SimpleGraph`, `V(·)`, `E(·)`, `Sym2`) for everything graph-theoretic.

All the `def`s, `lemma`s and `theorem`s below are fully proved (no `sorry`). The two headline
results are `chromaticNum_le_cliqueNum_intervalGraph` (the hard direction) and
`isPerfect_intervalGraph`. The proof actually formalized is a clean reorganization of the source:
instead of building the sorted enumeration and the greedy colouring by hand, we do a strong
induction on `𝓘.card`, removing at each step the interval of *largest* key — the key insight
(`exists_common_point`) is precisely the source's two-case argument, and it shows that the removed
vertex together with its already-coloured neighbours forms a clique, so one colour stays free.

`(P)` notes flag observations about the `GraphLib` definitions themselves — the convenience /
inconvenience we are hunting for.
-/

namespace GraphLib.Playground
open GraphLib

/-! ## A. Translating the notions into Lean

We first pin down, as genuine Lean definitions, every notion the proof uses. -/

/-
### "is an interval"

`(S)`  A set `I ⊆ ℝ` is an interval iff `∀ x, y ∈ I, [x, y] ⊆ I`.

`(L)`  This is exactly Mathlib's `Set.OrdConnected`:
       `Set.ordConnected_iff : OrdConnected s ↔ ∀ x ∈ s, ∀ y ∈ s, x ≤ y → Icc x y ⊆ s`.
       (The extra `x ≤ y` is harmless: `Icc x y = ∅` when `y < x`.) We keep the *general* notion
       of interval, exactly as the source does — Problem 2's "closed" is just the special case
       where the infimum, when finite, is attained.
-/

/-
### The interval graph `G = ⟨𝓘, E, ∈⟩`

`(S)`  `G := ⟨𝓘, E := {{I, J} ∈ 𝓟₌₂(𝓘) | I ∩ J ≠ ∅}, ∈⟩`; a simple undirected graph with `∈` as
       endpoint relation.

`(L)`  We use `GraphLib.SimpleGraph (Set ℝ)`: vertices are intervals (`α := Set ℝ`), an edge is an
       unordered pair `Sym2 (Set ℝ)`, and `∈ : α → Sym2 α → Prop` is the built-in `Sym2`
       membership — i.e. `Sym2` *is* the "`∈` as endpoint function". The two structural axioms of
       `SimpleGraph` (`incidence'`, `loopless'`) are discharged below.

`(P)`  Convenience: edges as `Sym2` make "unordered pair `{I, J}`" and the endpoint relation free,
       and `loopless'` is exactly the `I ≠ J` we wanted. Friction: the collection `𝓘` is most
       naturally a `Finset (Set ℝ)` (to get `|𝓘| < ℵ₀`), but `vertexSet` is a `Set α`, so we coerce
       `↑𝓘` and pay small `Finset.mem_coe` bridges. Modeling note: a `Finset (Set ℝ)` is a genuine
       *set* of intervals, so equal intervals collapse — matching the source's `𝓘 ⊆ 𝒫(ℝ)` (a set),
       but losing multiplicity if one wanted a multiset of intervals.
-/

/-- The interval graph of a finite collection `𝓘` of intervals: vertices are the intervals,
and two *distinct* intervals are adjacent iff they intersect. -/
def intervalGraph (𝓘 : Finset (Set ℝ)) : SimpleGraph (Set ℝ) where
  vertexSet := ↑𝓘
  edgeSet := {e | ∃ A ∈ 𝓘, ∃ B ∈ 𝓘, A ≠ B ∧ (A ∩ B).Nonempty ∧ e = s(A, B)}
  incidence' := by
    rintro e ⟨A, hA, B, hB, _, _, rfl⟩ v hv
    rw [Sym2.mem_iff] at hv
    rcases hv with rfl | rfl
    · exact Finset.mem_coe.mpr hA
    · exact Finset.mem_coe.mpr hB
  loopless' := by
    rintro e ⟨A, _, B, _, hne, _, rfl⟩
    rw [Sym2.mk_isDiag_iff]
    exact hne

namespace SimpleGraph
variable {α : Type*}

/-
### Clique and clique number `ω`

`(S)`  A clique is a subfamily `C` whose members pairwise intersect; `ω(G) = k :=
       max {|E| | E ⊆ 𝓘 ∧ ∀ I, J ∈ E, I ≠ J → I ∩ J ≠ ∅}`.

`(L)`  A clique is a set of vertices that are pairwise adjacent (`s(a,b) ∈ E(G)`). `ω(G)` is the
       `sSup` of the cardinalities of finite cliques; for a finite graph the sup is attained, so
       this `sSup` is the source's `max`.
-/

/-- `C` is a clique of `G`: a set of vertices that are pairwise adjacent. -/
def IsClique (G : SimpleGraph α) (C : Set α) : Prop :=
  C ⊆ V(G) ∧ ∀ ⦃a⦄, a ∈ C → ∀ ⦃b⦄, b ∈ C → a ≠ b → s(a, b) ∈ E(G)

/-- The clique number `ω(G)`: the supremum of cardinalities of finite cliques. -/
noncomputable def cliqueNum (G : SimpleGraph α) : ℕ :=
  sSup {n | ∃ C : Finset α, IsClique G ↑C ∧ C.card = n}

/-
### Proper coloring and chromatic number `χ`

`(S)`  A proper coloring is `f : 𝓘 → k` with `|f[e]| = 2` for every edge `e` (the two endpoints
       get different colors); `χ(G)` is the least number of colors admitting such an `f`.

`(L)`  `f : ↥V(G) → κ` is proper iff adjacent vertices get distinct colours. `χ(G)` is the `sInf`
       of those `n` admitting a proper colouring `f : ↥V(G) → Fin n` of the vertices.

`(P)`  `|f[e]| = 2` (source) becomes the cleaner `f a ≠ f b` once edges are `Sym2`: an edge already
       *is* its two endpoints, so "the image of the edge has size 2" is just "endpoints differ".

`(P)`  The faithful translation colours the *vertices*: a coloring is `f : ↥V(G) → Fin n`, a
       function out of the vertex set as a subtype — exactly the source's `f : 𝓘 → k`. The pitfall
       to avoid is colouring the whole carrier type, `f : α → Fin n`: with `V(G) = ∅` but
       `α = Set ℝ` nonempty there is no total `f : α → Fin 0`, which would spuriously force `χ ≥ 1`.
       Colouring `↥V(G)` has no such issue — the empty graph carries the empty colouring into
       `Fin 0`, giving `χ = 0 = ω`. (The lesson: keep a colouring's domain equal to `V(G)`.)
-/

/-- `f` is a proper coloring of `G`: adjacent vertices receive distinct colors. -/
def IsProperColoring {κ : Type*} (G : SimpleGraph α) (f : ↥(V(G)) → κ) : Prop :=
  ∀ a b : ↥(V(G)), s(↑a, ↑b) ∈ E(G) → f a ≠ f b

/-- The chromatic number `χ(G)`: the least `n` admitting a proper colouring of the vertices into
`Fin n`. -/
noncomputable def chromaticNum (G : SimpleGraph α) : ℕ :=
  sInf {n | ∃ f : ↥(V(G)) → Fin n, IsProperColoring G f}

/-
### Perfection

`(S)`  Source remark: a finite simple graph `H` is perfect `⟺ χ(H) = ω(H)`.

`(L)`  We take that remark as the working definition for a single graph.

`(P)`  The *standard* definition of a perfect graph quantifies over all induced subgraphs:
       `H` perfect `⟺ ∀ induced H' ⊆ H, χ(H') = ω(H')`. The source's single-graph version is
       weaker. For interval graphs the gap is harmless because the class is hereditary: every
       induced subgraph of an interval graph is again an interval graph (`intervalGraph` of a
       sub-`Finset`), so `χ = ω` for the whole class follows from the single-graph statement
       applied to each sub-`Finset`. We only formalize the single-graph statement here.
-/

/-- A finite graph is *perfect* (single-graph sense of the source remark) when `χ(G) = ω(G)`. -/
def IsPerfect (G : SimpleGraph α) : Prop := chromaticNum G = cliqueNum G

end SimpleGraph

/-! ## A'. Analytic helpers and graph lemmas

Concrete Lean machinery backing the `(L)` translations: the sorting key `κ`, the unfolding of the
interval graph's vertex/edge sets, and the basic clique bookkeeping. -/

open SimpleGraph Set

open Classical in
/-- A chosen point of a set (junk `0` if empty), used to pick witnesses in finite families. -/
noncomputable def pick (S : Set ℝ) : ℝ := if h : S.Nonempty then h.choose else 0

lemma pick_mem {S : Set ℝ} (h : S.Nonempty) : pick S ∈ S := by
  unfold pick; rw [dif_pos h]; exact h.choose_spec

/-
### The sorting key `κ`

`(S)`  `κ(I) = (inf I, 0)` if `inf I ∈ I`, else `(inf I, 1)`, ordered lexicographically.

`(L)`  `inf` of a subset of `ℝ` naturally lives in `EReal` (`= sInf (↑'' I)`); `Attained I` records
       whether it is realized by a point of `I`; `flag` turns that into `Fin 2` (`0` if attained);
       `key I := toLex (lo I, flag I) : EReal ×ₗ Fin 2`, whose `≤` is `≤_lex` (`toLex_le_toLex`).
-/

/-- The (extended-real) infimum of an interval. -/
noncomputable def lo (S : Set ℝ) : EReal := sInf (Real.toEReal '' S)

/-- The infimum of `S` is attained by a point of `S`. -/
def Attained (S : Set ℝ) : Prop := lo S ∈ Real.toEReal '' S

open Classical in
/-- Tie-break flag of the key: `0` if the infimum is attained, `1` otherwise. -/
noncomputable def flag (S : Set ℝ) : Fin 2 := if Attained S then 0 else 1

/-- The lexicographic sorting key `κ`. -/
noncomputable def key (S : Set ℝ) : EReal ×ₗ Fin 2 := toLex (lo S, flag S)

lemma lo_le_coe {S : Set ℝ} {x : ℝ} (hx : x ∈ S) : lo S ≤ (x : EReal) :=
  sInf_le ⟨x, hx, rfl⟩

lemma exists_lt_of_lo_lt {S : Set ℝ} {c : ℝ} (h : lo S < (c : EReal)) : ∃ y ∈ S, y < c := by
  by_contra hcon; push Not at hcon
  exact absurd h (not_lt.mpr (le_sInf (by rintro b ⟨y, hy, rfl⟩; exact_mod_cast hcon y hy)))

lemma flag_eq_zero_of_attained {S : Set ℝ} (h : Attained S) : flag S = 0 := by rw [flag, if_pos h]

lemma flag_eq_one_of_not_attained {S : Set ℝ} (h : ¬ Attained S) : flag S = 1 := by
  rw [flag, if_neg h]

lemma attained_of_flag_le {S : Set ℝ} (h : flag S ≤ 0) : Attained S := by
  by_contra hcon; rw [flag_eq_one_of_not_attained hcon] at h; exact absurd h (by decide)

lemma key_le_iff {J L : Set ℝ} :
    key J ≤ key L ↔ lo J < lo L ∨ (lo J = lo L ∧ flag J ≤ flag L) := by
  unfold key; exact Prod.Lex.toLex_le_toLex

/-! ### Unfolding the interval graph's vertex and edge sets -/

@[simp] lemma vertexSet_intervalGraph (𝓘 : Finset (Set ℝ)) :
    V(intervalGraph 𝓘) = (↑𝓘 : Set (Set ℝ)) := rfl

@[simp] lemma edgeSet_intervalGraph (𝓘 : Finset (Set ℝ)) :
    E(intervalGraph 𝓘) =
      {e | ∃ A ∈ 𝓘, ∃ B ∈ 𝓘, A ≠ B ∧ (A ∩ B).Nonempty ∧ e = s(A, B)} := rfl

/-- `(L)` adjacency in the interval graph: `s(A,B)` is an edge iff `A, B` are distinct members of
`𝓘` that intersect. This is the direct Lean reading of the source's edge relation. -/
lemma mem_edgeSet_intervalGraph {𝓘 : Finset (Set ℝ)} {A B : Set ℝ} :
    s(A, B) ∈ E(intervalGraph 𝓘) ↔ A ∈ 𝓘 ∧ B ∈ 𝓘 ∧ A ≠ B ∧ (A ∩ B).Nonempty := by
  rw [edgeSet_intervalGraph, Set.mem_setOf_eq]
  constructor
  · rintro ⟨A', hA', B', hB', hne', hAB', he⟩
    rw [Sym2.eq_iff] at he
    rcases he with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact ⟨hA', hB', hne', hAB'⟩
    · refine ⟨hB', hA', hne'.symm, ?_⟩
      rwa [Set.inter_comm]
  · rintro ⟨hA, hB, hne, hAB⟩
    exact ⟨A, hA, B, hB, hne, hAB, rfl⟩

/-! ### Clique bookkeeping -/

lemma isClique_empty (𝓘 : Finset (Set ℝ)) :
    IsClique (intervalGraph 𝓘) (↑(∅ : Finset (Set ℝ))) := by
  rw [Finset.coe_empty]; exact ⟨Set.empty_subset _, fun a ha => absurd ha (Set.notMem_empty a)⟩

lemma isClique_mono {𝓘₁ 𝓘₂ : Finset (Set ℝ)} (h : 𝓘₁ ⊆ 𝓘₂) {C : Set (Set ℝ)}
    (hC : IsClique (intervalGraph 𝓘₁) C) : IsClique (intervalGraph 𝓘₂) C := by
  obtain ⟨hsub, hadj⟩ := hC
  refine ⟨?_, ?_⟩
  · rw [vertexSet_intervalGraph] at hsub ⊢
    exact hsub.trans (Finset.coe_subset.mpr h)
  · intro a ha b hb hab
    have hedge := hadj ha hb hab
    rw [mem_edgeSet_intervalGraph] at hedge ⊢
    obtain ⟨ha𝓘, hb𝓘, hne, hint⟩ := hedge
    exact ⟨h ha𝓘, h hb𝓘, hne, hint⟩

/-- A family with a common point is a clique: pairwise intersection at `p` gives every edge. -/
lemma isClique_insert_of_common {𝓘 : Finset (Set ℝ)} {L : Set ℝ} (hL : L ∈ 𝓘)
    {N : Finset (Set ℝ)} (hNsub : ∀ J ∈ N, J ∈ 𝓘) {p : ℝ} (hpL : p ∈ L)
    (hpN : ∀ J ∈ N, p ∈ J) :
    IsClique (intervalGraph 𝓘) ↑(insert L N) := by
  constructor
  · intro A hA
    rw [vertexSet_intervalGraph]
    rw [Finset.coe_insert, Set.mem_insert_iff, Finset.mem_coe] at hA
    rcases hA with rfl | hAN
    · exact Finset.mem_coe.mpr hL
    · exact Finset.mem_coe.mpr (hNsub A hAN)
  · intro A hA B hB hAB
    rw [Finset.coe_insert, Set.mem_insert_iff, Finset.mem_coe] at hA hB
    rw [mem_edgeSet_intervalGraph]
    refine ⟨?_, ?_, hAB, p, ?_, ?_⟩
    · rcases hA with rfl | hAN; exacts [hL, hNsub A hAN]
    · rcases hB with rfl | hBN; exacts [hL, hNsub B hBN]
    · rcases hA with rfl | hAN; exacts [hpL, hpN A hAN]
    · rcases hB with rfl | hBN; exacts [hpL, hpN B hBN]

lemma cliqueNum_bddAbove (𝓘 : Finset (Set ℝ)) :
    BddAbove {n | ∃ C : Finset (Set ℝ), IsClique (intervalGraph 𝓘) ↑C ∧ C.card = n} := by
  refine ⟨𝓘.card, ?_⟩
  rintro n ⟨C, ⟨hsub, _⟩, rfl⟩
  refine Finset.card_le_card fun a ha => ?_
  have : a ∈ V(intervalGraph 𝓘) := hsub (Finset.mem_coe.mpr ha)
  rwa [vertexSet_intervalGraph, Finset.mem_coe] at this

lemma card_le_cliqueNum {𝓘 : Finset (Set ℝ)} {Q : Finset (Set ℝ)}
    (h : IsClique (intervalGraph 𝓘) ↑Q) : Q.card ≤ cliqueNum (intervalGraph 𝓘) := by
  apply le_csSup (cliqueNum_bddAbove 𝓘); exact ⟨Q, h, rfl⟩

lemma cliqueNum_mono {𝓘₁ 𝓘₂ : Finset (Set ℝ)} (hsub : 𝓘₁ ⊆ 𝓘₂) :
    cliqueNum (intervalGraph 𝓘₁) ≤ cliqueNum (intervalGraph 𝓘₂) := by
  apply csSup_le_csSup (cliqueNum_bddAbove 𝓘₂)
  · exact ⟨0, ∅, isClique_empty 𝓘₁, Finset.card_empty⟩
  · rintro m ⟨C, hC, rfl⟩
    exact ⟨C, isClique_mono hsub hC, rfl⟩

/-! ## C. The proof, written twice (set theory `(S)` / Lean `(L)`)

Throughout: `𝓘 : Finset (Set ℝ)`, `hI : ∀ A ∈ 𝓘, OrdConnected A`, `G := intervalGraph 𝓘`,
`n := 𝓘.card`, `k := cliqueNum G`.

--------------------------------------------------------------------------------
### Step 0 — Reduce the partition statement to `χ(G) ≤ k`

`(S)`  It suffices to show `χ(G) ≤ k`. Indeed, given a proper coloring `f : 𝓘 → k`, set
       `Eᵢ := f⁻¹[{i}]`. Then `𝓘 = ⋃_{i∈k} Eᵢ`, and if `I ≠ J` lie in the same `Eᵢ` but
       `I ∩ J ≠ ∅`, then `{I, J} ∈ E`, so `2 = |f[{I,J}]| = |{i}| = 1`, absurd; hence `I ∩ J = ∅`.
       So each `Eᵢ` is a family of pairwise disjoint intervals, the desired partition into `k`
       classes.

`(L)`  This packaging is `IsProperColoring` + `cliqueNum`/`chromaticNum`; the actual content is
       `chromaticNum_le_cliqueNum_intervalGraph` below. The colour classes are
       `fun i => 𝓘.filter (f · = i)`; disjointness inside a class is the contrapositive of
       `mem_edgeSet_intervalGraph` (intersecting distinct members are adjacent, hence differently
       coloured).

`(P)`  Convenience: with `Sym2` edges, `{I,J} ∈ E ⟺ I, J meet` is the single rewrite
       `mem_edgeSet_intervalGraph`, so "same colour ⇒ disjoint" is one contrapositive. Friction:
       the classes live as `Finset.filter`, but `IsProperColoring` quantifies over `V(G) = ↑𝓘`, so
       moving between the two costs small `Finset.mem_coe` steps — the recurring `Set`/`Finset` tax.

--------------------------------------------------------------------------------
### Step 1 — The graph is well-formed

`(S)`  `G = ⟨𝓘, E, ∈⟩` is a simple undirected graph (finite since `|𝓘| < ℵ₀`).

`(L)`  `intervalGraph 𝓘 : GraphLib.SimpleGraph (Set ℝ)`; its `incidence'`/`loopless'` fields are
       proved in the definition (`Sym2.mem_iff`, `Sym2.mk_isDiag_iff`). Finiteness is carried by
       `𝓘 : Finset _`.

`(P)`  Convenience: the two structural axioms cost two lines each, and `loopless'` is exactly the
       `I ≠ J` we wanted; finiteness sits on `𝓘 : Finset` rather than as a graph field, so there is
       no `Fintype V(G)` instance to thread through the proof.

--------------------------------------------------------------------------------
### Step 2 — The sorting key `κ`  (def `key`, lemma `key_le_iff`)

`(S)`  `κ(I) = (inf I, 0)` if `inf I ∈ I`, else `(inf I, 1)`, lexicographic.

`(L)`  `key I = toLex (lo I, flag I)` with `lo I : EReal`. `key_le_iff` is `toLex_le_toLex`.

`(P)`  `sInf : Set ℝ → ℝ` returns junk `0` on unbounded sets, so the faithful key is forced
       into `EReal` — a dependent-type-theory tax with no set-theoretic counterpart.

--------------------------------------------------------------------------------
### Step 3 — Order by `κ`; Step 4 — Greedy colour

`(S)`  Build a `κ`-increasing bijection `g : n → 𝓘` (insertion recursion), then colour greedily
       `f(g(i)) = min{c | no earlier neighbour has colour c}` (recursion on the prefix).

`(L)`  We do **not** materialize `g` and `f` separately. Both the sorting and the greedy recursion
       are absorbed into a single strong induction on `𝓘.card` (`color` below): at each step we
       *remove the interval `L` of largest `key`* (`Finset.exists_max_image`), colour the rest by
       the induction hypothesis, and give `L` a colour avoided by its already-coloured neighbours.
       Removing the largest key plays the role of "`g(n')` is last", so that *every* neighbour of
       `L` is an "earlier" neighbour — which is what makes Step 5/6 go through.

`(P)`  This is where the proof assistant is *shorter* than the hand proof: `Finset.sort`-style
       sorting and the greedy bookkeeping become a single `Finset.strongInductionOn`.

--------------------------------------------------------------------------------
### Step 5/6 — Earlier neighbours of `L` form a clique  (lemma `exists_common_point`)

`(S)`  Let `a := inf L`. The neighbours `J` of `L` (those meeting `L`, all with `κ(J) ≤ κ(L)`)
       share a point with `L`:
       • if `a ∈ L`, then `a ∈ J` for every such `J` (either `inf J = a` is attained, giving
         `a ∈ J`, or `inf J < a` and, as `J` is an interval reaching up into `L`, `a ∈ J`);
       • if `a ∉ L`, pick `ρ(J) ∈ J ∩ L` and let `x := min_J ρ(J) > a`; then `x ∈ L` and, as each
         `J` is an interval with `inf(J ∩ L) = a`, `x ∈ ]a, ρ(J)] ⊆ J`.
       Hence `{L} ∪ {neighbours}` all share a point, so they pairwise intersect: a clique.

`(L)`  `exists_common_point` produces a `p ∈ L` with `p ∈ J` for every neighbour, by exactly this
       case split on `Attained L` (the `flag`). The `< vs =` dichotomy comes from `key_le_iff`
       (`toLex_le_toLex`); reaching the common point uses `Set.OrdConnected.out`
       (`a ∈ Icc y x ⊆ J`) and `sInf` facts (`lo_le_coe`, `exists_lt_of_lo_lt`). The non-attained
       branch uses non-attainment to rule out `lo J = ↑p` (which would attain `lo L` at `p ∈ L`).
       `isClique_insert_of_common` then turns the common point into an honest `IsClique`, since for
       `intervalGraph` adjacency *is* "the two intervals meet" (`mem_edgeSet_intervalGraph`).

`(P)`  The geometric heart is stated *directly on graph edges* — no translation layer between
       "geometry" and "graph", which is the main convenience of the `SimpleGraph` definition here.

--------------------------------------------------------------------------------
### Step 7 — A free colour exists; Step 8 — `χ ≤ k = ω`

`(S)`  If all `k` colours were used by earlier neighbours, those neighbours `C` would satisfy
       `|C| ≥ k`, so `C ∪ {L}` is a clique of size `≥ k+1 > k = ω`, contradiction. Hence a colour
       stays free, the greedy colouring uses `≤ k` colours and is proper, so `χ(G) ≤ k`. With the
       general `ω ≤ χ`, and `ω = k`, we get `χ = ω`: `G` is perfect.

`(L)`  `card_le_cliqueNum` bounds the neighbour clique by `k`, so the neighbours use `< k` colours
       and a colour in `range k` is free (`color`). That yields a proper colouring bounded by `k`,
       i.e. `chromaticNum_le_cliqueNum_intervalGraph`. The easy direction
       `cliqueNum_le_chromaticNum_intervalGraph` injects a clique into the colours
       (`Finset.card_le_card_of_injOn`); `isPerfect_intervalGraph` is `le_antisymm`.

`(P)`  Both `ω` and `χ` land in plain `ℕ` (`sSup`/`sInf`), so the closing `le_antisymm` is literally
       `χ ≤ ω` paired with `ω ≤ χ`. Colouring the vertices `↥V(G)` (not the carrier `α`) is what
       makes the empty graph give `χ = 0 = ω` rather than a spurious `1 ≠ 0`.
-/

/-- **Step 5/6.** Let `L` be a (`key`-maximal) interval of `𝓘`. Every member of `𝓘` meeting `L`,
together with `L`, shares a common point. This is the source's two-case "common anchor" argument.
-/
lemma exists_common_point {𝓘 : Finset (Set ℝ)} (hOC : ∀ A ∈ 𝓘, Set.OrdConnected A)
    {L : Set ℝ} (hLne : L.Nonempty) (hmax : ∀ J ∈ 𝓘, key J ≤ key L)
    {N : Finset (Set ℝ)} (hN : ∀ J ∈ N, J ∈ 𝓘 ∧ (J ∩ L).Nonempty) :
    ∃ p, p ∈ L ∧ ∀ J ∈ N, p ∈ J := by
  by_cases hatt : Attained L
  · -- `inf L` is attained at some `a ∈ L`; the common point is `a`.
    have hflagL : flag L = 0 := flag_eq_zero_of_attained hatt
    obtain ⟨a, haL, hae⟩ := hatt
    refine ⟨a, haL, ?_⟩
    intro J hJ
    obtain ⟨hJ𝓘, hJL⟩ := hN J hJ
    have hkey : key J ≤ key L := hmax J hJ𝓘
    rw [key_le_iff] at hkey
    obtain ⟨x, hxJ, hxL⟩ := hJL
    rcases hkey with hlt | ⟨heq, hflag⟩
    · rw [← hae] at hlt
      obtain ⟨y, hyJ, hya⟩ := exists_lt_of_lo_lt hlt
      have hax : a ≤ x := by
        have hc := lo_le_coe hxL; rw [← hae] at hc; exact_mod_cast hc
      exact (hOC J hJ𝓘).out hyJ hxJ (Set.mem_Icc.mpr ⟨hya.le, hax⟩)
    · rw [hflagL] at hflag
      obtain ⟨z, hzJ, hze⟩ := attained_of_flag_le hflag
      have hza : z = a := by
        have h2 : (z : EReal) = (a : EReal) := by rw [hze, heq, ← hae]
        exact_mod_cast h2
      rwa [hza] at hzJ
  · -- `inf L` is not attained; the common point is the least chosen witness.
    have hflagL : flag L = 1 := flag_eq_one_of_not_attained hatt
    rcases N.eq_empty_or_nonempty with hNe | hNne
    · refine ⟨hLne.choose, hLne.choose_spec, ?_⟩
      intro J hJ
      rw [hNe] at hJ
      exact absurd hJ (Finset.notMem_empty J)
    · obtain ⟨p, hpmem, hple⟩ :=
        Finset.exists_min_image (N.image (fun J => pick (J ∩ L))) id (hNne.image _)
      rw [Finset.mem_image] at hpmem
      obtain ⟨J0, hJ0, hJ0p⟩ := hpmem
      have hpL : p ∈ L := by rw [← hJ0p]; exact (pick_mem (hN J0 hJ0).2).2
      refine ⟨p, hpL, ?_⟩
      intro J hJ
      obtain ⟨hJ𝓘, hJL⟩ := hN J hJ
      have hxJ : pick (J ∩ L) ∈ J ∩ L := pick_mem hJL
      have hpx : p ≤ pick (J ∩ L) := hple _ (Finset.mem_image_of_mem _ hJ)
      have hkey : key J ≤ key L := hmax J hJ𝓘
      rw [key_le_iff] at hkey
      have hloJle : lo J ≤ lo L := by rcases hkey with h | ⟨h, _⟩ <;> exact h.le
      have hpLle : lo L ≤ (p : EReal) := lo_le_coe hpL
      have hloJp : lo J ≤ (p : EReal) := hloJle.trans hpLle
      rcases lt_or_eq_of_le hloJp with hlt | heq
      · obtain ⟨y, hyJ, hyp⟩ := exists_lt_of_lo_lt hlt
        exact (hOC J hJ𝓘).out hyJ hxJ.1 (Set.mem_Icc.mpr ⟨hyp.le, hpx⟩)
      · exfalso
        have hloLp : lo L = (p : EReal) := le_antisymm hpLle (heq ▸ hloJle)
        exact hatt ⟨p, hpL, hloLp.symm⟩

/-- **Steps 3–7.** Strong induction on `𝓘.card`: an interval graph with clique number `≤ k`
admits a proper colouring whose colours on the vertices are `< k`. -/
theorem color : ∀ (k : ℕ) (𝓘 : Finset (Set ℝ)),
    (∀ A ∈ 𝓘, Set.OrdConnected A) → cliqueNum (intervalGraph 𝓘) ≤ k →
    ∃ g : Set ℝ → ℕ,
      (∀ ⦃A⦄, A ∈ 𝓘 → ∀ ⦃B⦄, B ∈ 𝓘 → s(A, B) ∈ E(intervalGraph 𝓘) → g A ≠ g B) ∧
      ∀ A ∈ 𝓘, g A < k := by
  intro k 𝓘
  induction 𝓘 using Finset.strongInductionOn with
  | _ 𝓘 IH =>
  intro hOC hk
  classical
  rcases 𝓘.eq_empty_or_nonempty with rfl | hne
  · -- empty graph: no vertices, no edges — the constant colouring is vacuously proper
    exact ⟨fun _ => 0, fun A hA => absurd hA (Finset.notMem_empty A),
      fun A hA => absurd hA (Finset.notMem_empty A)⟩
  · -- remove the `key`-maximal interval `L`
    obtain ⟨L, hL, hmax⟩ := Finset.exists_max_image 𝓘 key hne
    have hOC' : ∀ A ∈ 𝓘.erase L, Set.OrdConnected A := fun A hA => hOC A (Finset.mem_of_mem_erase hA)
    have hk' : cliqueNum (intervalGraph (𝓘.erase L)) ≤ k :=
      le_trans (cliqueNum_mono (Finset.erase_subset L 𝓘)) hk
    obtain ⟨f', hf'proper, hf'bound⟩ := IH (𝓘.erase L) (Finset.erase_ssubset hL) hOC' hk'
    set N := (𝓘.erase L).filter (fun J => (J ∩ L).Nonempty) with hNdef
    -- membership facts for `N`
    have hNmem : ∀ J ∈ N, J ∈ 𝓘 ∧ (J ∩ L).Nonempty := by
      intro J hJ
      rw [hNdef, Finset.mem_filter, Finset.mem_erase] at hJ
      exact ⟨hJ.1.2, hJ.2⟩
    have hLN : L ∉ N := by
      rw [hNdef, Finset.mem_filter, Finset.mem_erase]
      rintro ⟨⟨hne', _⟩, _⟩
      exact hne' rfl
    -- the clique `{L} ∪ N`
    have hclique : IsClique (intervalGraph 𝓘) ↑(insert L N) := by
      rcases L.eq_empty_or_nonempty with rfl | hLne
      · -- `L = ∅` meets nothing, so `N = ∅` and the clique is the singleton `{∅}`
        have hNe : N = ∅ := by
          rw [hNdef, Finset.filter_eq_empty_iff]
          exact fun J _ => by rw [Set.inter_empty]; exact Set.not_nonempty_empty
        rw [hNe]
        refine ⟨fun A hA => ?_, fun A hA B hB hAB => ?_⟩ <;>
          simp only [Finset.coe_insert, Finset.coe_empty, Set.mem_insert_iff,
            Set.mem_empty_iff_false, or_false] at hA
        · rw [vertexSet_intervalGraph, hA]; exact Finset.mem_coe.mpr hL
        · simp only [Finset.coe_insert, Finset.coe_empty, Set.mem_insert_iff,
            Set.mem_empty_iff_false, or_false] at hB
          exact absurd (hA.trans hB.symm) hAB
      · obtain ⟨p, hpL, hpN⟩ := exists_common_point hOC hLne hmax hNmem
        exact isClique_insert_of_common hL (fun J hJ => (hNmem J hJ).1) hpL hpN
    -- the neighbour set is smaller than `k`
    have hNcard : N.card < k := by
      have hcard := card_le_cliqueNum hclique
      rw [Finset.card_insert_of_notMem hLN] at hcard
      omega
    -- a free colour `c < k`
    have hfree : ∃ c, c < k ∧ ∀ J ∈ N, f' J ≠ c := by
      by_contra hcon
      push Not at hcon
      have hsub : Finset.range k ⊆ N.image f' := by
        intro c hc
        rw [Finset.mem_range] at hc
        obtain ⟨J, hJ, hJc⟩ := hcon c hc
        exact Finset.mem_image.mpr ⟨J, hJ, hJc⟩
      have h1 := Finset.card_le_card hsub
      have h2 : (N.image f').card ≤ N.card := Finset.card_image_le
      rw [Finset.card_range] at h1
      omega
    obtain ⟨c, hck, hcN⟩ := hfree
    -- update `f'` at `L`
    refine ⟨Function.update f' L c, ?_, ?_⟩
    · -- proper
      intro A hA B hB hAB
      rw [mem_edgeSet_intervalGraph] at hAB
      obtain ⟨_, _, hne, hint⟩ := hAB
      by_cases hAL : A = L
      · subst A
        rw [Function.update_self]
        have hBL : B ≠ L := hne.symm
        rw [Function.update_of_ne hBL]
        have hBN : B ∈ N := by
          rw [hNdef, Finset.mem_filter, Finset.mem_erase]
          exact ⟨⟨hBL, hB⟩, by rw [Set.inter_comm]; exact hint⟩
        exact (hcN B hBN).symm
      · rw [Function.update_of_ne hAL]
        by_cases hBL : B = L
        · subst B
          rw [Function.update_self]
          have hAN : A ∈ N := by
            rw [hNdef, Finset.mem_filter, Finset.mem_erase]
            exact ⟨⟨hAL, hA⟩, hint⟩
          exact hcN A hAN
        · rw [Function.update_of_ne hBL]
          refine hf'proper (Finset.mem_erase.mpr ⟨hAL, hA⟩) (Finset.mem_erase.mpr ⟨hBL, hB⟩) ?_
          rw [mem_edgeSet_intervalGraph]
          exact ⟨Finset.mem_erase.mpr ⟨hAL, hA⟩, Finset.mem_erase.mpr ⟨hBL, hB⟩, hne, hint⟩
    · -- colours stay `< k`
      intro A hA
      by_cases hAL : A = L
      · subst A; rw [Function.update_self]; exact hck
      · rw [Function.update_of_ne hAL]
        exact hf'bound A (Finset.mem_erase.mpr ⟨hAL, hA⟩)

/-! ## B. The headline results -/

/-- For any `k ≥ ω(G)`, the vertices admit a proper colouring into `Fin k`, read off from the total
colouring built by `color`. -/
lemma exists_coloring_le {𝓘 : Finset (Set ℝ)} (hI : ∀ A ∈ 𝓘, Set.OrdConnected A)
    {k : ℕ} (hk : cliqueNum (intervalGraph 𝓘) ≤ k) :
    ∃ f : ↥(V(intervalGraph 𝓘)) → Fin k, IsProperColoring (intervalGraph 𝓘) f := by
  obtain ⟨g, hg, hb⟩ := color k 𝓘 hI hk
  have hmem : ∀ a : ↥(V(intervalGraph 𝓘)), a.1 ∈ 𝓘 := fun a => a.2
  exact ⟨fun a => ⟨g a.1, hb a.1 (hmem a)⟩, fun a b hab => by
    simp only [ne_eq, Fin.mk.injEq]; exact hg (hmem a) (hmem b) hab⟩

/-- A proper colouring of the vertices into `Fin (χ G)` exists: the `χ`-set is nonempty by
`exists_coloring_le`, so its `sInf` is attained. -/
lemma exists_coloring_chromaticNum (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    ∃ f : ↥(V(intervalGraph 𝓘)) → Fin (chromaticNum (intervalGraph 𝓘)),
      IsProperColoring (intervalGraph 𝓘) f := by
  have h : cliqueNum (intervalGraph 𝓘) ∈
      {n | ∃ f : ↥(V(intervalGraph 𝓘)) → Fin n, IsProperColoring (intervalGraph 𝓘) f} :=
    exists_coloring_le hI le_rfl
  exact Nat.sInf_mem ⟨_, h⟩

/-- **Key inequality.** For an interval graph, `χ(G) ≤ ω(G)`. -/
theorem chromaticNum_le_cliqueNum_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    chromaticNum (intervalGraph 𝓘) ≤ cliqueNum (intervalGraph 𝓘) :=
  Nat.sInf_le (exists_coloring_le hI le_rfl)

/-- The reverse inequality `ω(G) ≤ χ(G)`, holding for every (finite) graph: a clique injects into
the colours. -/
theorem cliqueNum_le_chromaticNum_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    cliqueNum (intervalGraph 𝓘) ≤ chromaticNum (intervalGraph 𝓘) := by
  classical
  obtain ⟨f, hf⟩ := exists_coloring_chromaticNum 𝓘 hI
  apply csSup_le
  · exact ⟨0, ∅, isClique_empty 𝓘, Finset.card_empty⟩
  · rintro m ⟨C, hC, rfl⟩
    have key : ∀ A ∈ (↑C : Set (Set ℝ)), A ∈ V(intervalGraph 𝓘) := fun A hA => hC.1 hA
    calc C.card
        ≤ (Finset.range (chromaticNum (intervalGraph 𝓘))).card :=
          Finset.card_le_card_of_injOn
            (fun A => if h : A ∈ V(intervalGraph 𝓘) then (f ⟨A, h⟩).1 else 0)
            (fun A hA => Finset.mem_coe.mpr (Finset.mem_range.mpr (by
              simp only [dif_pos (key A hA)]; exact (f ⟨A, key A hA⟩).2)))
            (fun A hA B hB hAB => by
              simp only [dif_pos (key A hA), dif_pos (key B hB)] at hAB
              by_contra hne2
              exact hf ⟨A, key A hA⟩ ⟨B, key B hB⟩ (hC.2 hA hB hne2) (Fin.val_injective hAB))
      _ = chromaticNum (intervalGraph 𝓘) := Finset.card_range _

/-- The interval graph of a finite family of intervals is perfect: `χ(G) = ω(G)`. -/
theorem isPerfect_intervalGraph
    (𝓘 : Finset (Set ℝ)) (hI : ∀ A ∈ 𝓘, Set.OrdConnected A) :
    IsPerfect (intervalGraph 𝓘) :=
  le_antisymm (chromaticNum_le_cliqueNum_intervalGraph 𝓘 hI)
    (cliqueNum_le_chromaticNum_intervalGraph 𝓘 hI)

end GraphLib.Playground
